const INDEX_KEY = '_data/projects.json';
function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function slugify(v){return String(v||'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-+|-+$/g,'')}
async function load(bucket){const o=await bucket.get(INDEX_KEY);if(!o)return[];try{const v=await o.json();return Array.isArray(v)?v:[]}catch{return[]}}
async function save(bucket,projects){await bucket.put(INDEX_KEY,JSON.stringify(projects,null,2),{httpMetadata:{contentType:'application/json'}})}
function clean(input,existing={}){const title=String(input.title||'').trim();const photos=Array.isArray(input.photos)?input.photos.filter(p=>p&&typeof p.key==='string'&&p.key.startsWith('projects/')).map(p=>({key:p.key,role:['before','after','detail'].includes(p.role)?p.role:'detail'})):[];return{...existing,title,slug:slugify(title)||existing.id,location:String(input.location||'').trim(),service:String(input.service||'').trim(),description:String(input.description||'').trim(),published:Boolean(input.published),photos}}
export async function onRequestGet({env}){if(!env.MEDIA_BUCKET)return json({ok:false,error:'MEDIA_BUCKET binding is unavailable.'},500);return json({ok:true,projects:await load(env.MEDIA_BUCKET)})}
export async function onRequestPost({request,env}){if(!env.MEDIA_BUCKET)return json({ok:false,error:'MEDIA_BUCKET binding is unavailable.'},500);let input;try{input=await request.json()}catch{return json({ok:false,error:'Invalid project data.'},400)}let project=clean(input);if(!project.title)return json({ok:false,error:'Project title is required.'},400);if(!project.photos.length)return json({ok:false,error:'Add at least one photo.'},400);project={...project,id:crypto.randomUUID(),createdAt:new Date().toISOString()};const projects=await load(env.MEDIA_BUCKET);projects.unshift(project);await save(env.MEDIA_BUCKET,projects);return json({ok:true,project},201)}
export async function onRequestPut({request,env}){if(!env.MEDIA_BUCKET)return json({ok:false,error:'MEDIA_BUCKET binding is unavailable.'},500);let input;try{input=await request.json()}catch{return json({ok:false,error:'Invalid project data.'},400)}const projects=await load(env.MEDIA_BUCKET),i=projects.findIndex(p=>p.id===input.id);if(i<0)return json({ok:false,error:'Project not found.'},404);const project=clean(input,{...projects[i],updatedAt:new Date().toISOString()});if(!project.title)return json({ok:false,error:'Project title is required.'},400);if(!project.photos.length)return json({ok:false,error:'Add at least one photo.'},400);projects[i]=project;await save(env.MEDIA_BUCKET,projects);return json({ok:true,project})}
export async function onRequestDelete({request,env}){if(!env.MEDIA_BUCKET)return json({ok:false,error:'MEDIA_BUCKET binding is unavailable.'},500);let input;try{input=await request.json()}catch{return json({ok:false,error:'Invalid request.'},400)}const projects=await load(env.MEDIA_BUCKET),i=projects.findIndex(p=>p.id===input.id);if(i<0)return json({ok:false,error:'Project not found.'},404);const [removed]=projects.splice(i,1);await save(env.MEDIA_BUCKET,projects);return json({ok:true,removed:{id:removed.id,title:removed.title}})}